Ext.define('Aperitiv.store.Countries', {
    extend: 'Ext.data.ArrayStore',
    alias: 'store.countries',

    idProperty: 'isoCode',

    fields: ['isoCode', 'localizationCode', 'countryCode1', 'countryCode2', 'countryCode3', {
        name: 'localizationText',
        calculate: function (data) {
            return Translations.localize('{' + data.localizationCode + '}');
        }
    }],

    data: [
        ['AB', 'countries.ab', '+7 840', '+7 940', '+995 44'],
        ['AF', 'countries.af', '+93'],
        ['AX', 'countries.ax', '+358 18'],
        ['AL', 'countries.al', '+355'],
        ['DZ', 'countries.dz', '+213'],
        ['AS', 'countries.as', '+1 684'],
        ['AD', 'countries.ad', '+376'],
        ['AO', 'countries.ao', '+244'],
        ['AI', 'countries.ai', '+1 264'],
        ['AG', 'countries.ag', '+1 268'],
        ['AR', 'countries.ar', '+54'],
        ['AM', 'countries.am', '+374'],
        ['AW', 'countries.aw', '+297'],
        ['SH', 'countries.sh_ac', '+247'],
        ['AU', 'countries.au', '+61'],
        ['AU', 'countries.au_et', '+672'],
        ['AT', 'countries.at', '+43'],
        ['AZ', 'countries.az', '+994'],
        ['BS', 'countries.bs', '+1 242'],
        ['BH', 'countries.bh', '+973'],
        ['BD', 'countries.bd', '+880'],
        ['BB', 'countries.bb', '+1 246'],
        ['AG', 'countries.ag_bar', '+1 268'],
        ['BY', 'countries.by', '+375'],
        ['BE', 'countries.be', '+32'],
        ['BZ', 'countries.bz', '+501'],
        ['BJ', 'countries.bj', '+229'],
        ['BM', 'countries.bm', '+1 441'],
        ['BT', 'countries.bt', '+975'],
        ['BO', 'countries.bo', '+591'],
        ['BQ', 'countries.bq', '+599 7'],
        ['BA', 'countries.ba', '+387'],
        ['BW', 'countries.bw', '+267'],
        ['BR', 'countries.br', '+55'],
        ['IO', 'countries.io', '+246'],
        ['VG', 'countries.vg', '+1 284'],
        ['BN', 'countries.bn', '+673'],
        ['BG', 'countries.bg', '+359'],
        ['BF', 'countries.bf', '+226'],
        ['MY', 'countries.mm', '+95'],
        ['BI', 'countries.bi', '+257'],
        ['KH', 'countries.kh', '+855'],
        ['CM', 'countries.cm', '+237'],
        ['CA', 'countries.ca', '+1'],
        ['CV', 'countries.cv', '+238'],
        ['KY', 'countries.ky', '+1 345'],
        ['CF', 'countries.cf', '+236'],
        ['TD', 'countries.td', '+235'],
        ['CL', 'countries.cl', '+56'],
        ['CN', 'countries.cn', '+86'],
        ['CX', 'countries.cx', '+61'],
        ['CC', 'countries.cc', '+61'],
        ['CO', 'countries.co', '+57'],
        ['KM', 'countries.km', '+269'],
        ['CG', 'countries.cg', '+242'],
        ['CD', 'countries.cd', '+243'],
        ['CK', 'countries.ck', '+682'],
        ['CR', 'countries.cr', '+506'],
        ['CI', 'countries.ci', '+225'],
        ['HR', 'countries.hr', '+385'],
        ['CU', 'countries.cu', '+53'],
        ['CW', 'countries.cw', '+599 9'],
        ['CY', 'countries.cy', '+357'],
        ['CZ', 'countries.cz', '+420'],
        ['DK', 'countries.dk', '+45'],
        ['DG', 'countries.dg', '+246'],
        ['DJ', 'countries.dj', '+253'],
        ['DM', 'countries.dm', '+1 767'],
        ['DO', 'countries.do', '+1 809', '+1 829', '+1 849'],
        ['TL', 'countries.tl', '+670'],
        ['EC', 'countries.ec', '+593'],
        ['EG', 'countries.eg', '+20'],
        ['SV', 'countries.sv', '+503'],
        ['GQ', 'countries.gq', '+240'],
        ['ER', 'countries.er', '+291'],
        ['EE', 'countries.ee', '+372'],
        ['ET', 'countries.et', '+251'],
        ['FK', 'countries.fk', '+500'],
        ['FO', 'countries.fo', '+298'],
        ['FJ', 'countries.fj', '+679'],
        ['FI', 'countries.fi', '+358'],
        ['FR', 'countries.fr', '+33'],
        ['GF', 'countries.gf', '+594'],
        ['PF', 'countries.pf', '+689'],
        ['GA', 'countries.ga', '+241'],
        ['GM', 'countries.gm', '+220'],
        ['GE', 'countries.ge', '+995'],
        ['DE', 'countries.de', '+49'],
        ['GH', 'countries.gh', '+233'],
        ['GI', 'countries.gi', '+350'],
        ['GR', 'countries.gr', '+30'],
        ['GL', 'countries.gl', '+299'],
        ['GD', 'countries.gd', '+1 473'],
        ['GP', 'countries.gp', '+590'],
        ['GU', 'countries.gu', '+1 671'],
        ['GT', 'countries.gt', '+502'],
        ['GG', 'countries.gg', '+44'],
        ['GN', 'countries.gn', '+224'],
        ['GW', 'countries.gw', '+245'],
        ['GY', 'countries.gy', '+592'],
        ['HT', 'countries.ht', '+509'],
        ['HN', 'countries.hn', '+504'],
        ['HK', 'countries.hk', '+852'],
        ['HU', 'countries.hu', '+36'],
        ['IS', 'countries.is', '+354'],
        ['IN', 'countries.in', '+91'],
        ['ID', 'countries.id', '+62'],
        ['IR', 'countries.ir', '+98'],
        ['IQ', 'countries.iq', '+964'],
        ['IE', 'countries.ie', '+353'],
        ['IL', 'countries.il', '+972'],
        ['IT', 'countries.it', '+39'],
        ['JM', 'countries.jm', '+1 876'],
        ['SJ', 'countries.sj', '+47 79'],
        ['JP', 'countries.jp', '+81'],
        ['JE', 'countries.je', '+44'],
        ['JO', 'countries.jo', '+962'],
        ['KZ', 'countries.kz', '+7 6', '+7 7'],
        ['KE', 'countries.ke', '+254'],
        ['KI', 'countries.ki', '+686'],
        ['KP', 'countries.kp', '+850'],
        ['KR', 'countries.kr', '+82'],
        ['KW', 'countries.kw', '+965'],
        ['KG', 'countries.kg', '+996'],
        ['LA', 'countries.la', '+856'],
        ['LV', 'countries.lv', '+371'],
        ['LB', 'countries.lb', '+961'],
        ['LS', 'countries.ls', '+266'],
        ['LR', 'countries.lr', '+231'],
        ['LY', 'countries.ly', '+218'],
        ['LI', 'countries.li', '+423'],
        ['LT', 'countries.lt', '+370'],
        ['LU', 'countries.lu', '+352'],
        ['MO', 'countries.mo', '+853'],
        ['MK', 'countries.mk', '+389'],
        ['MG', 'countries.mg', '+261'],
        ['MW', 'countries.mw', '+265'],
        ['MY', 'countries.my', '+60'],
        ['MV', 'countries.mv', '+960'],
        ['ML', 'countries.ml', '+223'],
        ['MT', 'countries.mt', '+356'],
        ['MH', 'countries.mh', '+692'],
        ['MQ', 'countries.mq', '+596'],
        ['MR', 'countries.mr', '+222'],
        ['MU', 'countries.mu', '+230'],
        ['YT', 'countries.yt', '+262'],
        ['MX', 'countries.mx', '+52'],
        ['FM', 'countries.fm', '+691'],
        ['MD', 'countries.md', '+373'],
        ['MC', 'countries.mc', '+377'],
        ['MN', 'countries.mn', '+976'],
        ['ME', 'countries.me', '+382'],
        ['MS', 'countries.ms', '+1 664'],
        ['MA', 'countries.ma', '+212'],
        ['MZ', 'countries.mz', '+258'],
        ['NA', 'countries.na', '+264'],
        ['NR', 'countries.nr', '+674'],
        ['NP', 'countries.np', '+977'],
        ['NL', 'countries.nl', '+31'],
        ['NC', 'countries.nc', '+687'],
        ['NZ', 'countries.nz', '+64'],
        ['NI', 'countries.ni', '+505'],
        ['NE', 'countries.ne', '+227'],
        ['NG', 'countries.ng', '+234'],
        ['NU', 'countries.nu', '+683'],
        ['NF', 'countries.nf', '+672'],
        ['MP', 'countries.mp', '+1 670'],
        ['NO', 'countries.no', '+47'],
        ['OM', 'countries.om', '+968'],
        ['PK', 'countries.pk', '+92'],
        ['PW', 'countries.pw', '+680'],
        ['PS', 'countries.ps', '+970'],
        ['PA', 'countries.pa', '+507'],
        ['PG', 'countries.pg', '+675'],
        ['PY', 'countries.py', '+595'],
        ['PE', 'countries.pe', '+51'],
        ['PH', 'countries.ph', '+63'],
        ['PN', 'countries.pn', '+64'],
        ['PL', 'countries.pl', '+48'],
        ['PT', 'countries.pt', '+351'],
        ['PR', 'countries.pr', '+1 787', '+1 939'],
        ['QA', 'countries.qa', '+974'],
        ['RE', 'countries.re', '+262'],
        ['RO', 'countries.ro', '+40'],
        ['RU', 'countries.ru', '+7'],
        ['RW', 'countries.rw', '+250'],
        ['BL', 'countries.bl', '+590'],
        ['SH', 'countries.sh', '+290'],
        ['KN', 'countries.kn', '+1 869'],
        ['LC', 'countries.lc', '+1 758'],
        ['MF', 'countries.mf', '+590'],
        ['PM', 'countries.pm', '+508'],
        ['VC', 'countries.vc', '+1 784'],
        ['WS', 'countries.ws', '+685'],
        ['SM', 'countries.sm', '+378'],
        ['ST', 'countries.st', '+239'],
        ['SA', 'countries.sa', '+966'],
        ['SN', 'countries.sn', '+221'],
        ['RS', 'countries.rs', '+381'],
        ['SC', 'countries.sc', '+248'],
        ['SL', 'countries.sl', '+232'],
        ['SG', 'countries.sg', '+65'],
        ['BQ', 'countries.nl_bq3', '+599 3'],
        ['SX', 'countries.sx', '+1 721'],
        ['SK', 'countries.sk', '+421'],
        ['SI', 'countries.si', '+386'],
        ['SB', 'countries.sb', '+677'],
        ['SO', 'countries.so', '+252'],
        ['ZA', 'countries.za', '+27'],
        ['GS', 'countries.gs', '+500'],
        [false, 'countries.ge_so', '+995 34'],
        ['SS', 'countries.ss', '+211'],
        ['ES', 'countries.es', '+34'],
        ['LK', 'countries.lk', '+94'],
        ['SD', 'countries.sd', '+249'],
        ['SR', 'countries.sr', '+597'],
        ['SJ', 'countries.sj_no', '+47 79'],
        ['SZ', 'countries.sz', '+268'],
        ['SE', 'countries.se', '+46'],
        ['CH', 'countries.ch', '+41'],
        ['SY', 'countries.sy', '+963'],
        ['TW', 'countries.tw', '+886'],
        ['TJ', 'countries.tj', '+992'],
        ['TZ', 'countries.tz', '+255'],
        ['TH', 'countries.th', '+66'],
        ['TG', 'countries.tg', '+228'],
        ['TK', 'countries.tk', '+690'],
        ['TO', 'countries.to', '+676'],
        ['TT', 'countries.tt', '+1 868'],
        ['TN', 'countries.tn', '+216'],
        ['TR', 'countries.tr', '+90'],
        ['TM', 'countries.tm', '+993'],
        ['TC', 'countries.tc', '+1 649'],
        ['TV', 'countries.tv', '+688'],
        ['UG', 'countries.ug', '+256'],
        ['UA', 'countries.ua', '+380'],
        ['AE', 'countries.ae', '+971'],
        ['UK', 'countries.uk', '+44'],
        ['US', 'countries.us', '+1'],
        ['UY', 'countries.uy', '+598'],
        ['VI', 'countries.vi', '+1 340'],
        ['UZ', 'countries.uz', '+998'],
        ['VU', 'countries.vu', '+678'],
        ['VE', 'countries.ve', '+58'],
        ['VA', 'countries.va', '+39 06 698', '+379'],
        ['VN', 'countries.vn', '+84'],
        ['WF', 'countries.wf', '+681'],
        ['YE', 'countries.ye', '+967'],
        ['ZM', 'countries.zm', '+260'],
        [false, 'countries.tz_uk', '+255'],
        ['ZW', 'countries.zw', '+263']
    ]
});